---
deployment:
  tasks:
    - export DEPLOYPATH=/home/christi5/admin.christianmeza.com/
    - /bin/cp SistemaAgencia/index.html $DEPLOYPATH
    - /bin/cp SistemaAgencia/home.php $DEPLOYPATH
    
    - /bin/cp -r SistemaAgencia/css $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/dist $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/config $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/img $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/js $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/pages $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/plantillas $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/plugins $DEPLOYPATH
    - /bin/cp -r SistemaAgencia/vistas $DEPLOYPATH
    
    - /bin/cp pagina/home.php /home/christi5/pagina.christianmeza.com/
    - /bin/cp pagina/home2.php /home/christi5/pagina.christianmeza.com/
    - /bin/cp pagina/index.php /home/christi5/pagina.christianmeza.com/
    - /bin/cp pagina/registrate.php /home/christi5/pagina.christianmeza.com/
    
    - /bin/cp -r pagina/config /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/contactform /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/css /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/img /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/js /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/lib /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/plantilla /home/christi5/pagina.christianmeza.com/
    - /bin/cp -r pagina/vistas /home/christi5/pagina.christianmeza.com/